// const URL_ROOT = 'http://192.168.151.199:9999'
const URL_ROOT = 'http://127.0.0.1:60000'

export const SEND_SUBMENU = URL_ROOT + '/send_submenu'
export const SEND_SEARCH = URL_ROOT + '/send_search'
export const GET_TABLE_DATA = URL_ROOT + '/getTableData'
export const GET_PDF = URL_ROOT + '/get_pdf'
export const PREDICT = URL_ROOT + '/predict'
export const SEND_ITEMSPERPAGE = URL_ROOT + '/send_items_per_page'
export const SEND_SEARCHITEMS = URL_ROOT + '/send_search_items'
export const SEND_LIST = URL_ROOT + '/send_list'
export const SEND_EDIT = URL_ROOT + '/send_edit'
export const GET_MODEL_DATA = URL_ROOT + '/get_model_data'
export const GENERATE_CODE = URL_ROOT + '/generate_code'
export const GET_DLL = URL_ROOT + '/get_dll'

export const GET_LINE_DATA = URL_ROOT + '/get_line_data'
export const SEND_SELECTED_LINE = URL_ROOT + '/send_selected_line'
export const SEND_SELECTED_DESIGN = URL_ROOT + '/send_selected_design'
export const SEND_SELECTED_YEAR = URL_ROOT + '/send_selected_year'
export const UPLOAD_LINE = URL_ROOT + '/upload_line'
export const SELECT_LINES = URL_ROOT + '/select_lines'
export const DELETE_LINES = URL_ROOT + '/delete_lines'
export const SEND_EDIT_LINES = URL_ROOT + '/send_edit_lines'
export const EDIT_LINES = URL_ROOT + '/edit_lines'
export const EDIT_LINE_HEADER = URL_ROOT + '/edit_line_header'
export const EDIT_MATERIAL_HEADER = URL_ROOT + '/edit_material_header'
export const EXPORT_LINE = URL_ROOT + '/export_line'
export const EXPORT_MATERIAL = URL_ROOT + '/export_material'
export const EXPORT_PRODUCT = URL_ROOT + '/export_product'

export const GET_MATERIAL_DATA = URL_ROOT + '/get_material_data'
export const SELECTED_TYPE = URL_ROOT + '/send_selected_type'
export const SELECTED_TYPE1 = URL_ROOT + '/send_selected_type1'
export const SELECTED_TYPE2 = URL_ROOT + '/send_selected_type2'
export const SELECTED_GRADE = URL_ROOT + '/send_selected_grade'
export const UPLOAD_MATERIAL = URL_ROOT + '/upload_material'
export const SELECT_MATERIALS = URL_ROOT + '/select_materials'
export const DELETE_MATERIALS = URL_ROOT + '/delete_materials'
export const EDIT_MATERIALS = URL_ROOT + '/edit_materials'

export const GET_PRODUCT_DATA = URL_ROOT + '/get_product_data'
export const SEND_SELECTED_PLINE = URL_ROOT + '/send_selected_pline'
export const SEND_SELECTED_GRADENAME = URL_ROOT + '/send_selected_grade_name'
export const SEND_SELECTED_PROSHIFT = URL_ROOT + '/send_selected_proshift'
export const SEND_SELECTED_TIME = URL_ROOT + '/send_selected_time'
export const SEND_SELECTED_WIDTH = URL_ROOT + '/send_selected_width'
export const SEND_SELECTED_THICK = URL_ROOT + '/send_selected_thick'
export const UPLOAD_PRODUCT = URL_ROOT + '/upload_product'
export const SELECT_PRODUCTS = URL_ROOT + '/select_products'
export const DELETE_PRODUCTS = URL_ROOT + '/delete_products'

export const LOGIN = URL_ROOT + '/login'
export const GET_TIME = URL_ROOT + '/get_time'
